mads.exe BREAKOUT+.ASM -d:EASY -o:BREAKOUT+_EASY.XEX -t:BREAKOUT+_EASY.lab -l:BREAKOUT+_EASY.lst
mads.exe BREAKOUT+.ASM -d:NORMAL -o:BREAKOUT+_NORMAL.XEX -t:BREAKOUT+_NORMAL.lab -l:BREAKOUT+_NORMAL.lst
mads.exe BREAKOUT+.ASM -d:HARD -o:BREAKOUT+_HARD.XEX -t:BREAKOUT+_HARD.lab -l:BREAKOUT+_HARD.lst
